export const questions = [
  {
    id: 1,
    question: 'What does the "var" keyword mean in JavaScript?',
    code: "var",
    options: ["Declares a new block-scoped variable", "Declares a new function", "Declares a new global variable", "Declares a new constant"],
    answer: "Declares a new global variable",
  },
  {
    id: 2,
    question: "When collecting information, what does the following syntax mean?",
    code: `<span class="array">[]</span>`,
    options: ["An empty array", "An empty object", "Vue", "Java"],
    answer: "An empty array",
  },
  {
    id: 3,
    question: 'What is the purpose of the "let" keyword in JavaScript?',
    code: "let",
    options: ["Declares a new block-scoped variable", "Declares a new function", "Declares a new global variable", "Declares a new constant"],
    answer: "Declares a new block-scoped variable",
  },
  {
    id: 4,
    question: "What is the result of the following expression:",
    code: `<span class="magenta">console</span><span class="white">.</span><span class="function">log</span>(<span class="blue">3</span> + <span class="blue">2</span> + <span class="orange">"7"</span>)<span class="white">;</span>`,
    options: ["12", "327", "57", "NaN"],
    answer: "57",
  },
  {
    id: 5,
    question: 'What is the purpose of the "const" keyword in JavaScript?',
    code: "const",
    options: ["Declares a new block-scoped variable", "Declares a new function", "Declares a new global variable", "Declares a new constant"],
    answer: "Declares a new constant",
  },
  {
    id: 6,
    question: "What is the output of the following code?",
    code: `<span class="magenta">console</span><span class="white">.</span><span class="function">log</span>(typeof <span class="orange">undefined</span>)<span class="white">;</span>`,
    options: ["null", "undefined", "object", "string"],
    answer: "undefined",
  },
  {
    id: 7,
    question: 'What does the "===" operator do in JavaScript?',
    code: `===`,
    options: ["Checks for equality of values", "Checks for equality of values and types", "Assigns a value to a variable", "Concatenates strings"],
    answer: "Checks for equality of values and types",
  },
  {
    id: 8,
    question: 'What does the "!" operator (exclamation mark) represent in JavaScript?',
    code: `!`,
    options: ["Logical AND", "Logical OR", "Logical NOT", "Conditional operator"],
    answer: "Logical NOT",
  },
  {
    id: 9,
    question: "What is the result of the following expression?",
    code: '<span class="magenta">console</span><span class="white">.</span><span class="function">log</span>(<span class="orange">"5"</span> - <span class="function">3</span>)<span class="white">;</span>',
    options: ["2", "8", "NaN", "TypeError"],
    answer: "2",
  },
  {
    id: 10,
    question: "What is the output of the following code?",
    code: `<span class="magenta">console</span><span class="white">.</span><span class="function">log</span>(<span class="function">2</span> + <span class="function">2</span> * <span class="function">3</span>)<span class="white">;</span>`,
    options: ["6", "8", "10", "SyntaxError"],
    answer: "8",
  },
  {
    id: 11,
    question: "What does the Array.isArray() function check?",
    code: `<span class="red">Array</span><span class="white">.</span><span class="function">isArray</span>()<span class="white">;</span>`,
    options: ["If a value is an array", "If a value is a string", "If a value is a number", "If a value is an object"],
    answer: "If a value is an array",
  },
  {
    id: 12,
    question: "What is the output of the following code?",
    code: '<span class="magenta">console</span><span class="white">.</span><span class="function">log</span>(<span class="orange">"Hello"</span> + <span class="function">5</span>)<span class="white">;</span>',
    options: ["Hello5", "Hello", "5", "TypeError"],
    answer: "Hello5",
  },
  {
    id: 13,
    question: "What is the result of the following expression?",
    code: '<span class="red">Boolean</span>(<span class="orange">"false"</span>)<span class="white">;</span>',
    options: ["true", "false", "TypeError", "NaN"],
    answer: "true",
  },
  {
    id: 14,
    question: "What is the output of the following code?",
    code: `<span class="magenta">console</span><span class="white">.</span><span class="function">log</span>(<span class="function">10</span> % <span class="function">3</span>)<span class="white">;</span>`,
    options: ["3", "10", "1", "0"],
    answer: "1",
  },
  {
    id: 15,
    question: "What does the typeof operator return for an array?",
    code: `<span class="magenta">console</span><span class="white">.</span><span class="function">log</span>(typeof <span class="array">[]</span>)<span class="white">;</span>`,
    options: ["array", "object", "array-like", "TypeError"],
    answer: "object",
  },
  {
    id: 16,
    question: "What is the output of the following code?",
    code: '<span class="magenta">console</span><span class="white">.</span><span class="function">log</span>(<span class="orange">"Hello"</span> === <span class="orange">"hello"</span>)<span class="white">;</span>',
    options: ["true", "false", "TypeError", "NaN"],
    answer: "false",
  },
  {
    id: 17,
    question: 'What is the purpose of the "map" function in JavaScript?',
    code: `<span class="magenta">array</span><span class="white">.</span><span class="function">map</span>(<span class="magenta">callback</span>)<span class="white">;</span>`,
    options: ["Iterates over an array and modifies each element", "Creates a new array with the results of calling a callback function on every element", "Filters the elements of an array based on a condition", "Checks if any element in the array satisfies a condition"],
    answer: "Creates a new array with the results of calling a callback function on every element",
  },
  {
    id: 18,
    question: "Which keyword is used to define a function in JavaScript?",
    code: "function",
    options: ["method", "func", "define", "function"],
    answer: "function",
  },
  {
    id: 19,
    question: "What is the result of the following expression?",
    code: '<span class="magenta">console</span><span class="white">.</span><span class="function">log</span>(<span class="orange">"5"</span> + <span class="function">2</span> + <span class="function">3</span>)<span class="white">;</span>',
    options: ["523", "10", "15", "Error"],
    answer: "523",
  },
  {
    id: 20,
    question: "What is the output of the following code? ",
    code: `<span class="magenta">console</span><span class="white">.</span><span class="function">log</span>(typeof <span class="orange">null</span>)<span class="white">;</span>`,
    options: ["object", "null", "undefined", "TypeError"],
    answer: "object",
  },
];
